---
- name: Deploy Website 
  hosts: all
  become: true
  tasks:
    - name: latest version of httpd 
      ansible.builtin.yum:
        name:
          - git
          - httpd
        state: latest
    - name: Pull file from source
      ansible.builtin.git:
        repo: http://gitlab.kdinesh.in/root/sampleweb.git
        dest: /var/www/html
    - name: httpd enabled and running
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
